import TempModel from "../../models/TempModel";
import Temp from "../../types/client/Temp";

/**
 * Temporarily save a passkey challenge for verification, expires after 1 minute
 * @param uid the UID of the chef
 * @param challenge the randomly generated challenge for the client
 */
export const savePasskeyChallenge = async (uid: string, challenge: string) => {
  const challengeData: Temp = {
    _id: uid,
    expiresAt: new Date(Date.now() + 60_000), // 60s
    challenge,
  };

  try {
    // If the user requested another challenge before the timeout, replace the existing challenge
    const doc = await TempModel.findOneAndReplace({ _id: uid }, challengeData, {
      upsert: true,
      returnDocument: "after",
    }).exec();
    console.log(
      `Successfully saved passkey challenge for chef ${doc._id} to the DB`
    );
  } catch (error) {
    console.error(`Failed to save passkey challenge for chef ${uid}:`, error);
  }
};

/**
 * Get the passkey challenge for a chef
 *
 * **Note:** This may return `null` if the challenge expired after 1 minute
 * @param uid the UID of the chef
 * @returns all the challenge data associated with the chef, or `null` if it couldn't be found
 */
export const getPasskeyChallenge = async (
  uid: string
): Promise<Temp | null> => {
  try {
    return await TempModel.findById(uid).exec();
  } catch (error) {
    console.error(`Failed to get passkey challenge for chef ${uid}:`, error);
    return null;
  }
};

/**
 * Temporarily save a PKCE challenge for verification, expires after 5 minutes
 * @param state the state generated by an OAuth provider
 * @param codeVerifier the randomly generated challenge for authorization
 */
export const savePKCEChallenge = async (
  state: string,
  codeVerifier: string
) => {
  const challengeData: Temp = {
    _id: state,
    expiresAt: new Date(Date.now() + 300_000), // 5 mins
    challenge: codeVerifier,
  };

  try {
    // State should be random, but account for rare collisions
    const doc = await TempModel.findOneAndReplace(
      { _id: state },
      challengeData,
      {
        upsert: true,
        returnDocument: "after",
      }
    ).exec();
    console.log(
      `Successfully saved PKCE challenge for state ${doc._id} to the DB`
    );
  } catch (error) {
    console.error(`Failed to save PKCE challenge for state ${state}:`, error);
  }
};

/**
 * Get the PKCE challenge for an OAuth provider
 *
 * **Note:** This may return `null` if the challenge expired after 5 minutes
 * @param state the state generated by an OAuth provider
 * @returns all the challenge data associated with the state, or `null` if it couldn't be found
 */
export const getPKCEChallenge = async (state: string): Promise<Temp | null> => {
  try {
    return await TempModel.findById(state).exec();
  } catch (error) {
    console.error(`Failed to get PKCE challenge for state ${state}:`, error);
    return null;
  }
};
