services:
  web:
    # Docker Compose defaults to the master branch
    build: https://github.com/Abhiek187/ez-recipes-web.git#main
    image: ez-recipes-web

  server:
    build: .
    image: ez-recipes-server
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - API_KEY=$API_KEY
