name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker compose -f docker-compose.yml build server
      - name: Run tests inside the container
        env:
          API_KEY: ${{ secrets.API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: docker compose run --rm server npm test
