name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ez-recipes-server-ci:$(date +%s)
      - name: Run tests inside the container
        run: docker run ez-recipes-server-ci npm test
