name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: docker-compose -f docker-compose.yml up -d --build server
      - name: Run tests inside the container
        run: docker run --rm ez-recipes-server npm test
