import { Digest } from "./Digest";
import { Images } from "./Images";
import { Ingredient } from "./Ingredient";
import { Nutrients } from "./Nutrients";

export type Recipe = {
  uri: string;
  label: string;
  image: string;
  images: Images;
  source: string;
  url: string;
  shareAs: string;
  yield: number;
  dietLabels: [string];
  healthLabels: [string];
  cautions: [string];
  ingredientLines: [string];
  ingredients: [Ingredient];
  calories: number;
  glycemicIndex?: number;
  totalCO2Emissions?: number;
  co2EmissionsClass?: string;
  totalWeight: number;
  totalTime: number;
  cuisineType: [string];
  mealType: [string];
  dishType: [string];
  totalNutrients: Nutrients;
  totalDaily: Nutrients;
  digest: [Digest];
};
